In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
np.array([
    [95, 91],
    [92, 93],
    [98, 97],
    [100, 97]
])

array([[ 95,  91],
       [ 92,  93],
       [ 98,  97],
       [100,  97]])

In [4]:
arr2d = np.array([
    [95, 91],
    [92, 93],
    [98, 97],
    [100, 97]
])

In [5]:
arr2d.ndim

2

In [6]:
arr2d.shape

(4, 2)

In [7]:
arr2d.size

8

In [8]:
arr2d.dtype

dtype('int32')

In [9]:
pd.DataFrame(data=arr2d, columns=['A반', 'B반'])

A반  B반
0   95  91
1   92  93
2   98  97
3  100  97

In [10]:
df1 = pd.DataFrame(data=arr2d, columns=['A반', 'B반'])

In [11]:
df1.iloc[0]

A반    95
B반    91
Name: 0, dtype: int32

In [12]:
df1['A반']

0     95
1     92
2     98
3    100
Name: A반, dtype: int32

In [13]:
arr2d_2 = np.array([
    [87, 85],
    [89, 90]

])

In [14]:
arr2d_2

array([[87, 85],
       [89, 90]])

In [15]:
df2 = pd.DataFrame(data=arr2d_2, columns=['A반', 'B반'])

In [16]:
df2

A반  B반
0  87  85
1  89  90

In [17]:
arr2d_4 = np.array([
    [100],
    [100],
    [100],
    [100]
])

In [18]:
arr2d_4

array([[100],
       [100],
       [100],
       [100]])

In [19]:
df4 = pd.DataFrame(data=arr2d_4, columns=['D반'])

In [20]:
df4

D반
0  100
1  100
2  100
3  100

In [21]:
df1.join(df4)

A반  B반   D반
0   95  91  100
1   92  93  100
2   98  97  100
3  100  97  100

In [22]:
df2

A반  B반
0  87  85
1  89  90

In [23]:
pd.concat([df1, df2], ignore_index=True)

A반  B반
0   95  91
1   92  93
2   98  97
3  100  97
4   87  85
5   89  90

In [24]:
df1_df2 = pd.concat([df1, df2], ignore_index=True)

In [25]:
df1_df2

A반  B반
0   95  91
1   92  93
2   98  97
3  100  97
4   87  85
5   89  90

In [26]:
# 표를 만드는 일반적인 방법1

In [27]:
data1 = {'id': ['hong1', 'hong2', 'hong3', 'hong4', 'hong5'],
         '이름': ['홍일동', '홍이동', '홍삼동', '홍사동', '홍오동'],
         '키': [166,	168,	170,	172,	174]
         }

In [28]:
pd.DataFrame(data1)

id   이름    키
0  hong1  홍일동  166
1  hong2  홍이동  168
2  hong3  홍삼동  170
3  hong4  홍사동  172
4  hong5  홍오동  174

In [29]:
df1_stu = pd.DataFrame(data1)

In [30]:
df1_stu.columns

Index(['id', '이름', '키'], dtype='object')

In [31]:
df1_stu['이름']

0    홍일동
1    홍이동
2    홍삼동
3    홍사동
4    홍오동
Name: 이름, dtype: object

In [32]:
df1_stu.index

RangeIndex(start=0, stop=5, step=1)

In [33]:
df1_stu.set_index('id', inplace=True)

In [34]:
df1_stu

이름    키
id             
hong1  홍일동  166
hong2  홍이동  168
hong3  홍삼동  170
hong4  홍사동  172
hong5  홍오동  174

In [35]:
df1_stu.index

Index(['hong1', 'hong2', 'hong3', 'hong4', 'hong5'], dtype='object', name='id')

In [36]:
df1_stu.index.name

'id'

In [37]:
df1_stu.loc['hong3']

이름    홍삼동
키     170
Name: hong3, dtype: object

In [38]:
# 표를 만드는 일반적인 방법2

In [39]:
idx = ['hong1', 'hong2', 'hong3', 'hong4', 'hong5']

In [40]:
data2 = {
    '이름': ['홍일동', '홍이동', '홍삼동', '홍사동', '홍오동'],
    '키': [166,	168,	170,	172,	174]
}

In [41]:
pd.DataFrame(data2, index=pd.Index((idx), name='student'))

이름    키
student          
hong1    홍일동  166
hong2    홍이동  168
hong3    홍삼동  170
hong4    홍사동  172
hong5    홍오동  174

In [42]:
df_stu = pd.DataFrame(data2, index=pd.Index((idx), name='student'))

In [43]:
df_stu.index

Index(['hong1', 'hong2', 'hong3', 'hong4', 'hong5'], dtype='object', name='student')

In [44]:
df_stu.loc['hong4']

이름    홍사동
키     172
Name: hong4, dtype: object

In [45]:
df1 = pd.DataFrame({'Name': ['Harry Potter',	'David Baker',	'John Smith',	'Juan Martinez',	'Jane Connor'],
                    'Gender': ['Male',	'Male',	'Male',	'Male',	'Female'],
                    'Age': [23, 31, 22, 36, 30]
                    })

In [46]:
df1

Name  Gender  Age
0   Harry Potter    Male   23
1    David Baker    Male   31
2     John Smith    Male   22
3  Juan Martinez    Male   36
4    Jane Connor  Female   30

In [47]:
df2 = pd.DataFrame({'Name': ['John Smith',	'Alex Du Bois',	'Joanne Rowling',	'Jane Connor'],
                    'Position': ['Intern',	'Team Lead',	'Manager',	'Manager'],
                    'Wage': [25000, 75000, 90000, 70000]
                    })

In [48]:
df2

Name   Position   Wage
0      John Smith     Intern  25000
1    Alex Du Bois  Team Lead  75000
2  Joanne Rowling    Manager  90000
3     Jane Connor    Manager  70000

In [49]:
df1.merge(df2, on='Name', how='inner')

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [50]:
df1.merge(df2, on='Name')

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [51]:
df1.merge(df2)

Name  Gender  Age Position   Wage
0   John Smith    Male   22   Intern  25000
1  Jane Connor  Female   30  Manager  70000

In [52]:
df1.merge(df2, on='Name', how='left')

Name  Gender  Age Position     Wage
0   Harry Potter    Male   23      NaN      NaN
1    David Baker    Male   31      NaN      NaN
2     John Smith    Male   22   Intern  25000.0
3  Juan Martinez    Male   36      NaN      NaN
4    Jane Connor  Female   30  Manager  70000.0

In [53]:
df1.merge(df2, on='Name', how='right')

Name  Gender   Age   Position   Wage
0      John Smith    Male  22.0     Intern  25000
1    Alex Du Bois     NaN   NaN  Team Lead  75000
2  Joanne Rowling     NaN   NaN    Manager  90000
3     Jane Connor  Female  30.0    Manager  70000

In [54]:
df1.merge(df2, on='Name', how='outer')

Name  Gender   Age   Position     Wage
0    Alex Du Bois     NaN   NaN  Team Lead  75000.0
1     David Baker    Male  31.0        NaN      NaN
2    Harry Potter    Male  23.0        NaN      NaN
3     Jane Connor  Female  30.0    Manager  70000.0
4  Joanne Rowling     NaN   NaN    Manager  90000.0
5      John Smith    Male  22.0     Intern  25000.0
6   Juan Martinez    Male  36.0        NaN      NaN

In [55]:
# 엑셀에서 데이터 가져오기

In [57]:
pd.read_excel('1.xlsx')

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [58]:
pd.read_excel('1.xlsx')

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [60]:
pd.read_excel('1.xlsx', sheet_name='2학기')

학생   국   영    수
0  A  80  90  100
1  B  90  95  100
2  C  95  70  100
3  D  70  85  100
4  E  75  90  100

In [61]:
df_stu_score_1 = pd.read_excel('1.xlsx', sheet_name='1학기')

In [62]:
df_stu_score_1.head()

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [63]:
df_stu_score_1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   학생      5 non-null      object
 1   국       5 non-null      int64 
 2   영       5 non-null      int64 
 3   수       5 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 288.0+ bytes


In [64]:
df_stu_score_1.describe()

국          영          수
count   5.000000   5.000000   5.000000
mean   82.000000  86.000000  84.000000
std    10.368221   9.617692   7.416198
min    70.000000  70.000000  75.000000
25%    75.000000  85.000000  80.000000
50%    80.000000  90.000000  85.000000
75%    90.000000  90.000000  85.000000
max    95.000000  95.000000  95.000000

In [65]:
df_stu_score_1.index

RangeIndex(start=0, stop=5, step=1)

In [66]:
df_stu_score_1_idx = df_stu_score_1.set_index('학생')

In [67]:
df_stu_score_1_idx

국   영   수
학생            
A   80  90  85
B   90  95  95
C   95  70  75
D   70  85  80
E   75  90  85

In [68]:
df_stu_score_1_idx.index

Index(['A', 'B', 'C', 'D', 'E'], dtype='object', name='학생')

In [69]:
df_stu_score_1_idx.loc['A']

국    80
영    90
수    85
Name: A, dtype: int64

In [70]:
print("%.2f" % df_stu_score_1_idx.loc['A'].mean())
print("%.2f" % df_stu_score_1_idx.loc['B'].mean())
print("%.2f" % df_stu_score_1_idx.loc['C'].mean())
print("%.2f" % df_stu_score_1_idx.loc['D'].mean())
print("%.2f" % df_stu_score_1_idx.loc['E'].mean())

85.00
93.33
80.00
78.33
83.33


In [71]:
df_stu_score_1.values

array([['A', 80, 90, 85],
       ['B', 90, 95, 95],
       ['C', 95, 70, 75],
       ['D', 70, 85, 80],
       ['E', 75, 90, 85]], dtype=object)

In [72]:
df_stu_score_1

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [73]:
df_stu_score_1_drop = df_stu_score_1.drop('학생', axis=1)

In [74]:
df_stu_score_1_drop

국   영   수
0  80  90  85
1  90  95  95
2  95  70  75
3  70  85  80
4  75  90  85

In [75]:
df_stu_score_1_drop.values

array([[80, 90, 85],
       [90, 95, 95],
       [95, 70, 75],
       [70, 85, 80],
       [75, 90, 85]], dtype=int64)

In [76]:
df_stu_score_1_drop.values.mean()

84.0

In [77]:
df_stu_score_1.sort_values(by='국', ascending=False)

학생   국   영   수
2  C  95  70  75
1  B  90  95  95
0  A  80  90  85
4  E  75  90  85
3  D  70  85  80

In [78]:
stu_mean = [df_stu_score_1_idx.loc['A'].mean(), df_stu_score_1_idx.loc['B'].mean(), df_stu_score_1_idx.loc['C'].mean(),
            df_stu_score_1_idx.loc['D'].mean(), df_stu_score_1_idx.loc['E'].mean()]

In [79]:
df_stu_score_1['stu_mean'] = stu_mean

In [80]:
df_stu_score_1

학생   국   영   수   stu_mean
0  A  80  90  85  85.000000
1  B  90  95  95  93.333333
2  C  95  70  75  80.000000
3  D  70  85  80  78.333333
4  E  75  90  85  83.333333

In [82]:
df_stu_score_1.sort_values(by='stu_mean', ascending=False)

학생   국   영   수   stu_mean
1  B  90  95  95  93.333333
0  A  80  90  85  85.000000
4  E  75  90  85  83.333333
2  C  95  70  75  80.000000
3  D  70  85  80  78.333333

In [ ]:
# 데이터 요약시 유용한 피벗테이블 

In [83]:
df_stu_score_1

학생   국   영   수   stu_mean
0  A  80  90  85  85.000000
1  B  90  95  95  93.333333
2  C  95  70  75  80.000000
3  D  70  85  80  78.333333
4  E  75  90  85  83.333333

In [88]:
df_stu_score_1_drop=df_stu_score_1.drop("학생",axis=1)

In [89]:
df_stu_score_1_idx=df_stu_score_1.set_index('학생')

In [90]:
df_stu_score_1.values

array([['A', 80, 90, 85, 85.0],
       ['B', 90, 95, 95, 93.33333333333333],
       ['C', 95, 70, 75, 80.0],
       ['D', 70, 85, 80, 78.33333333333333],
       ['E', 75, 90, 85, 83.33333333333333]], dtype=object)

## 피벗테이블

In [99]:
data = { 'Date': ['2023-01-01', '2023-01-01','2023-01-01', '2023-01-02', '2023-01-02', '2023-01-03'], 
        'Category': ['A', 'B', 'A','A', 'B', 'A'], 'Value': [10, 20, 50, 15, 25, 10] }

In [100]:
df = pd.DataFrame(data)

In [101]:
df

Date Category  Value
0  2023-01-01        A     10
1  2023-01-01        B     20
2  2023-01-01        A     50
3  2023-01-02        A     15
4  2023-01-02        B     25
5  2023-01-03        A     10

In [105]:
df.columns

Index(['Date', 'Category', 'Value'], dtype='object')

In [115]:
pd.pivot_table(df, index= 'Date', columns='Category', values='Value', aggfunc='mean')

Category       A     B
Date                  
2023-01-01  30.0  20.0
2023-01-02  15.0  25.0
2023-01-03  10.0   NaN

## 데이터프레임 객체. 통계관련 메서드

In [116]:
df_stu_score_1 = pd.read_excel('1.xlsx', sheet_name='1학기')

In [117]:
df_stu_score_1

학생   국   영   수
0  A  80  90  85
1  B  90  95  95
2  C  95  70  75
3  D  70  85  80
4  E  75  90  85

In [120]:
df_stu_score_1.columns

Index(['학생', '국', '영', '수'], dtype='object')

In [123]:
df_stu_score_1.drop('학생', axis=1 , inplace=True)

In [124]:
df_stu_score_1

국   영   수
0  80  90  85
1  90  95  95
2  95  70  75
3  70  85  80
4  75  90  85

In [125]:
df_stu_score_1.mean(axis=1) # 행평균

0    85.000000
1    93.333333
2    80.000000
3    78.333333
4    83.333333
dtype: float64

In [126]:
df_stu_score_1.mean(axis=0) # 열평균

국    82.0
영    86.0
수    84.0
dtype: float64

In [127]:
df_stu_score_1.values.mean() # 전체평균 

84.0