In [57]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()

Species  Weight  Length  Diagonal   Height   Width
0   Bream   242.0    25.4      30.0  11.5200  4.0200
1   Bream   290.0    26.3      31.2  12.4800  4.3056
2   Bream   340.0    26.5      31.1  12.3778  4.6961
3   Bream   363.0    29.0      33.5  12.7300  4.4555
4   Bream   430.0    29.0      34.0  12.4440  5.1340

In [ ]:
fish.columns

In [ ]:
fish['Species']

In [ ]:
fish[['Species','Weight']]

In [ ]:
fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

In [3]:
fish_input =fish[['Weight', 'Length', 'Diagonal', 'Height', 'Width']].values

In [2]:
fish_target = fish['Species'].to_numpy()

In [58]:
from sklearn.model_selection import train_test_split

In [59]:
train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target,shuffle=True, random_state=42)

In [60]:
from sklearn.preprocessing import StandardScaler

In [47]:
sc=StandardScaler()

In [61]:
sc.fit(train_input)
train_scaled =sc.transform(train_input)
test_scaled =sc.transform(test_input)

## 로지스틱 회귀로 이진 분류 수행하기

In [10]:
pd.DataFrame(fish_target).value_counts()

0        
Perch        56
Bream        35
Roach        20
Pike         17
Smelt        14
Parkki       11
Whitefish     6
Name: count, dtype: int64

In [11]:
train_target

array(['Bream', 'Pike', 'Smelt', 'Perch', 'Parkki', 'Roach', 'Perch',
       'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Perch', 'Parkki',
       'Perch', 'Bream', 'Smelt', 'Perch', 'Roach', 'Bream', 'Pike',
       'Bream', 'Pike', 'Perch', 'Parkki', 'Bream', 'Perch', 'Pike',
       'Bream', 'Perch', 'Parkki', 'Roach', 'Perch', 'Bream', 'Roach',
       'Perch', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach', 'Pike',
       'Perch', 'Smelt', 'Pike', 'Roach', 'Perch', 'Parkki', 'Perch',
       'Bream', 'Perch', 'Smelt', 'Perch', 'Parkki', 'Smelt', 'Perch',
       'Perch', 'Roach', 'Bream', 'Perch', 'Perch', 'Roach', 'Roach',
       'Perch', 'Perch', 'Bream', 'Roach', 'Bream', 'Roach', 'Parkki',
       'Perch', 'Perch', 'Perch', 'Perch', 'Pike', 'Pike', 'Perch',
       'Bream', 'Perch', 'Bream', 'Whitefish', 'Pike', 'Bream', 'Bream',
       'Roach', 'Perch', 'Pike', 'Bream', 'Pike', 'Parkki', 'Roach',
       'Perch', 'Roach', 'Smelt', 'Whitefish', 'Roach', 'Perch', 'Bream',
       'Whitefi

In [49]:
train_scaled

array([[-0.40464242, -0.21359052,  0.01349752,  0.43943874, -0.33536111],
       [-0.23185172, -0.08643352,  0.1595162 ,  0.67177771, -0.12049917],
       [-0.05186141, -0.05817641,  0.14734797,  0.64704329,  0.1732809 ],
       [ 0.03093413,  0.29503748,  0.43938532,  0.73228265, -0.00772675],
       [ 0.27212115,  0.29503748,  0.50022643,  0.663065  ,  0.50272083],
       [ 0.34411728,  0.39393737,  0.58540399,  0.94342069,  0.34729199],
       [ 0.52410759,  0.39393737,  0.56106755,  1.08309029,  0.61143074],
       [ 0.1281289 ,  0.43632304,  0.62190866,  0.71776146,  0.16869176],
       [ 0.34411728,  0.43632304,  0.63407688,  1.04083364,  0.28439822],
       [ 0.52410759,  0.53522293,  0.76792733,  1.09448942,  0.37136615],
       [ 0.43411243,  0.57760859,  0.76792733,  1.10325054,  0.48030176],
       [ 0.52410759,  0.57760859,  0.76792733,  1.12953388,  0.26243055],
       [ 0.52410759,  0.64825137,  0.79226378,  0.98136939, -0.07355455],
       [-0.05186141,  0.71889415,  0.9

In [13]:
train_scaled[ (train_target == 'Bream') | (train_target == 'Smelt')]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174],
       [-1.0824759 , -1.61150165, -1.62162731, -1.7000674 , -1.92815631],
       [ 0.10337949,  0.04717013,  0.23714575,  0.88445197,  0.41799764],
       [ 1.49668216,  1.03112796,  1.21864741,  2.44274986,  1.40289707],
       [ 0.23004337,  0.23459067,  0.42823457,  1.3336029 ,  0.39983213],
       [-0.42579405, -0.29018684, -0.11028847,  0.65627104, -0.26107519],
       [ 1.28557569,  0.70314202,  0.89727076,  1.98228866,  1.06683526],
       [ 0.93373158,  0.60943175,  0.83646978,  1.85150445,  0.97832415],
       [ 0.80706771,  0.60943175,  0.81041221,  1.63137406,  1.0255057 ],
       [-1.07262426, -1.52716241, -1.5

In [14]:
train_bream_smelt = train_scaled[ (train_target == 'Bream') | (train_target == 'Smelt')]
target_bream_smelt = train_target[ (train_target == 'Bream') | (train_target == 'Smelt')]

In [16]:
type(train_bream_smelt)

numpy.ndarray

In [17]:
train_bream_smelt[:5,:]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174]])

In [19]:
target_bream_smelt

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Bream', 'Smelt',
       'Bream', 'Smelt', 'Smelt', 'Bream', 'Bream', 'Bream', 'Bream',
       'Bream', 'Bream', 'Bream', 'Bream', 'Smelt', 'Bream', 'Smelt',
       'Smelt', 'Bream', 'Smelt', 'Bream', 'Bream'], dtype=object)

In [20]:
target_bream_smelt[:5]

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream'], dtype=object)

In [21]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

LogisticRegression()

In [22]:
lr.classes_

array(['Bream', 'Smelt'], dtype=object)

In [23]:
train_bream_smelt

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174],
       [-1.0824759 , -1.61150165, -1.62162731, -1.7000674 , -1.92815631],
       [ 0.10337949,  0.04717013,  0.23714575,  0.88445197,  0.41799764],
       [ 1.49668216,  1.03112796,  1.21864741,  2.44274986,  1.40289707],
       [ 0.23004337,  0.23459067,  0.42823457,  1.3336029 ,  0.39983213],
       [-0.42579405, -0.29018684, -0.11028847,  0.65627104, -0.26107519],
       [ 1.28557569,  0.70314202,  0.89727076,  1.98228866,  1.06683526],
       [ 0.93373158,  0.60943175,  0.83646978,  1.85150445,  0.97832415],
       [ 0.80706771,  0.60943175,  0.81041221,  1.63137406,  1.0255057 ],
       [-1.07262426, -1.52716241, -1.5

In [24]:
train_bream_smelt[:5]

array([[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672],
       [-1.0858536 , -1.68646987, -1.70848587, -1.70159849, -2.0044758 ],
       [ 0.63818253,  0.56257661,  0.73223951,  1.64473401,  0.50705737],
       [ 0.30041219,  0.23459067,  0.42823457,  1.36042157,  0.22329758],
       [ 0.9027693 ,  0.70314202,  0.88858491,  1.89027545,  0.85537174]])

In [31]:
lr.predict(train_bream_smelt[:5])

array(['Bream', 'Smelt', 'Bream', 'Bream', 'Bream'], dtype=object)

In [30]:
print(lr.predict_proba(train_bream_smelt[:5]))

[[0.99760007 0.00239993]
 [0.02737325 0.97262675]
 [0.99486386 0.00513614]
 [0.98585047 0.01414953]
 [0.99767419 0.00232581]]


In [32]:
print(lr.coef_, lr.intercept_)

[[-0.40451732 -0.57582787 -0.66248158 -1.01329614 -0.73123131]] [-2.16172774]


In [38]:
fish.columns

Index(['Species', 'Weight', 'Length', 'Diagonal', 'Height', 'Width'], dtype='object')

In [35]:
lr.coef_[0][0]

-0.40451731516033246

In [40]:
train_bream_smelt[:5][0][0]

0.919657820086829

In [ ]:
[ 0.91965782,  0.60943175,  0.81041221,  1.85194896,  1.00075672]

In [ ]:
# z=lr.coef_[0][0]*Weight + lr.coef_[0][1]*Length + lr.coef_[0][2]*Diagonal + lr.coef_[0][3]*Height * lr.coef_[0][4]*Width + lr.intercept_

In [52]:
(-0.40451732*0.91965782) + (-0.57582787*0.60943175) + (-0.66248158*0.81041221)+(-1.01329614*1.85194896)+(-0.73123131*1.00075672) + -2.16172774

-6.029913584510324

In [43]:
lr.decision_function(train_bream_smelt[:5])

array([-6.02991358,  3.57043428, -5.26630496, -4.24382314, -6.06135688])

In [53]:
import numpy as np

In [55]:
1 - (1 / ( 1 + np.exp(-(-6.02991358))))

0.9976000716417482

In [54]:
1 / ( 1 + np.exp(-(-6.02991358)))

0.0023999283582517646

## 로지스틱 회귀로 다중 분류 수행하기

In [56]:
lr = LogisticRegression(C=20, max_iter=1000)

In [65]:
lr2 = LogisticRegression(C=10, max_iter=1000)

In [68]:
lr3 = LogisticRegression(C=20, max_iter=5000)

In [71]:
lr4 = LogisticRegression(C=20, max_iter=100)

In [ ]:
1 / ( 1 + np.exp(-(-6.02991358)))

0.0023999283582517646

In [62]:
lr.fit(train_scaled, train_target)

LogisticRegression(C=20, max_iter=1000)

In [66]:
lr2.fit(train_scaled, train_target)

LogisticRegression(C=10, max_iter=1000)

In [69]:
lr3.fit(train_scaled, train_target)

LogisticRegression(C=20, max_iter=5000)

In [72]:
lr4.fit(train_scaled, train_target)

LogisticRegression(C=20)

In [ ]:
1 / ( 1 + np.exp(-(-6.02991358)))

0.0023999283582517646

In [63]:
print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

0.9327731092436975
0.925


In [67]:
print(lr2.score(train_scaled, train_target))
print(lr2.score(test_scaled, test_target))

0.9159663865546218
0.925


In [70]:
print(lr3.score(train_scaled, train_target))
print(lr3.score(test_scaled, test_target))

0.9327731092436975
0.925


In [73]:
print(lr4.score(train_scaled, train_target))
print(lr4.score(test_scaled, test_target))

0.9327731092436975
0.925


In [74]:
print(lr.predict(test_scaled[:5]))

['Perch' 'Smelt' 'Pike' 'Roach' 'Perch']


In [75]:
lr.predict(test_scaled)

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch', 'Bream', 'Smelt',
       'Roach', 'Perch', 'Pike', 'Bream', 'Perch', 'Bream', 'Parkki',
       'Bream', 'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Smelt',
       'Bream', 'Bream', 'Bream', 'Bream', 'Perch', 'Perch', 'Roach',
       'Smelt', 'Smelt', 'Pike', 'Perch', 'Perch', 'Pike', 'Bream',
       'Perch', 'Roach', 'Roach', 'Parkki', 'Perch'], dtype=object)

In [77]:
len(lr.predict(test_scaled))

40

In [76]:
test_target

array(['Perch', 'Smelt', 'Pike', 'Whitefish', 'Perch', 'Bream', 'Smelt',
       'Roach', 'Perch', 'Pike', 'Bream', 'Whitefish', 'Bream', 'Parkki',
       'Bream', 'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Smelt',
       'Bream', 'Bream', 'Bream', 'Bream', 'Perch', 'Perch', 'Whitefish',
       'Smelt', 'Smelt', 'Pike', 'Perch', 'Perch', 'Pike', 'Bream',
       'Perch', 'Roach', 'Roach', 'Parkki', 'Perch'], dtype=object)

In [78]:
len(test_target)

40

In [79]:
pred_value=lr.predict(test_scaled)

In [80]:
pd.Series(pred_value)

0      Perch
1      Smelt
2       Pike
3      Roach
4      Perch
5      Bream
6      Smelt
7      Roach
8      Perch
9       Pike
10     Bream
11     Perch
12     Bream
13    Parkki
14     Bream
15     Bream
16     Perch
17     Perch
18     Perch
19     Bream
20     Smelt
21     Bream
22     Bream
23     Bream
24     Bream
25     Perch
26     Perch
27     Roach
28     Smelt
29     Smelt
30      Pike
31     Perch
32     Perch
33      Pike
34     Bream
35     Perch
36     Roach
37     Roach
38    Parkki
39     Perch
dtype: object

In [81]:
pres_values_series=pd.Series(pred_value)

In [82]:
real_values_series=pd.Series(test_target)

In [84]:
test_target

array(['Perch', 'Smelt', 'Pike', 'Whitefish', 'Perch', 'Bream', 'Smelt',
       'Roach', 'Perch', 'Pike', 'Bream', 'Whitefish', 'Bream', 'Parkki',
       'Bream', 'Bream', 'Perch', 'Perch', 'Perch', 'Bream', 'Smelt',
       'Bream', 'Bream', 'Bream', 'Bream', 'Perch', 'Perch', 'Whitefish',
       'Smelt', 'Smelt', 'Pike', 'Perch', 'Perch', 'Pike', 'Bream',
       'Perch', 'Roach', 'Roach', 'Parkki', 'Perch'], dtype=object)

In [85]:
df1=pd.DataFrame(pres_values_series)

In [86]:
df1['test_target'] = test_target

In [88]:
# 93%

In [89]:
3 / 39

0.07692307692307693

In [90]:
1 - (3 / 39)

0.9230769230769231

In [87]:
df1

0 test_target
0    Perch       Perch
1    Smelt       Smelt
2     Pike        Pike
3    Roach   Whitefish
4    Perch       Perch
5    Bream       Bream
6    Smelt       Smelt
7    Roach       Roach
8    Perch       Perch
9     Pike        Pike
10   Bream       Bream
11   Perch   Whitefish
12   Bream       Bream
13  Parkki      Parkki
14   Bream       Bream
15   Bream       Bream
16   Perch       Perch
17   Perch       Perch
18   Perch       Perch
19   Bream       Bream
20   Smelt       Smelt
21   Bream       Bream
22   Bream       Bream
23   Bream       Bream
24   Bream       Bream
25   Perch       Perch
26   Perch       Perch
27   Roach   Whitefish
28   Smelt       Smelt
29   Smelt       Smelt
30    Pike        Pike
31   Perch       Perch
32   Perch       Perch
33    Pike        Pike
34   Bream       Bream
35   Perch       Perch
36   Roach       Roach
37   Roach       Roach
38  Parkki      Parkki
39   Perch       Perch

In [91]:
lr.predict_proba(test_scaled[:5])

array([[7.15677704e-06, 1.35523407e-02, 8.41952847e-01, 3.04290993e-04,
        1.34839427e-01, 6.77873989e-03, 2.56519777e-03],
       [7.00705929e-09, 2.59742644e-03, 4.40982954e-02, 3.29538635e-05,
        7.37357170e-03, 9.45892428e-01, 5.31709193e-06],
       [1.87019732e-05, 2.80057801e-06, 3.40026974e-02, 9.34383821e-01,
        1.52274563e-02, 1.63347112e-02, 2.98118201e-05],
       [1.08847153e-02, 3.39566539e-02, 3.05427052e-01, 6.45094515e-03,
        5.66821647e-01, 7.26113153e-05, 7.63863751e-02],
       [4.47372387e-06, 3.68054511e-04, 9.04258921e-01, 2.35657202e-03,
        8.92019909e-02, 2.47024462e-03, 1.33974349e-03]])

In [96]:
np.round(lr.predict_proba(test_scaled[:5]) )

array([[0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.]])

In [98]:
lr.predict(test_scaled[:5])

array(['Perch', 'Smelt', 'Pike', 'Roach', 'Perch'], dtype=object)

In [99]:
lr.classes_

array(['Bream', 'Parkki', 'Perch', 'Pike', 'Roach', 'Smelt', 'Whitefish'],
      dtype=object)

In [97]:
np.round(lr.predict_proba(test_scaled[:5]) ,2)

array([[0.  , 0.01, 0.84, 0.  , 0.13, 0.01, 0.  ],
       [0.  , 0.  , 0.04, 0.  , 0.01, 0.95, 0.  ],
       [0.  , 0.  , 0.03, 0.93, 0.02, 0.02, 0.  ],
       [0.01, 0.03, 0.31, 0.01, 0.57, 0.  , 0.08],
       [0.  , 0.  , 0.9 , 0.  , 0.09, 0.  , 0.  ]])